In [1]:
# ==========================================
# MULTICLASS CLASSIFICATION (LOGISTIC REGRESSION)
# REAL-LIFE EXAMPLE: Student Grade Prediction
# ==========================================

# Step 1: Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression

# Step 2: Create dataset
data = {
    "Marks": [35,40,45,50,55,60,65,70,75,80,85,90],
    "Grade": ["C","C","C","B","B","B","B","B","A","A","A","A"]
}

df = pd.DataFrame(data)

print("===== DATASET =====")
print(df)

# Step 3: Define X and y
X = df[["Marks"]]
y = df["Grade"]

print("\n===== INPUT (X) =====")
print(X)

print("\n===== OUTPUT (y) =====")
print(y)

# Step 4: Create model
model = LogisticRegression(multi_class='ovr')

# Step 5: Train model
model.fit(X, y)

# Step 6: Predict classes
y_pred = model.predict(X)

print("\n===== PREDICTED CLASSES =====")
print(y_pred)

# Step 7: Predict probabilities
y_prob = model.predict_proba(X)

print("\n===== PREDICTED PROBABILITIES =====")
print(y_prob)

# Step 8: New prediction
new_student = pd.DataFrame({"Marks": [72]})

new_pred = model.predict(new_student)
new_prob = model.predict_proba(new_student)

print("\n===== NEW PREDICTION =====")
print("Predicted Grade:", new_pred[0])
print("Probabilities:", new_prob)

===== DATASET =====
    Marks Grade
0      35     C
1      40     C
2      45     C
3      50     B
4      55     B
5      60     B
6      65     B
7      70     B
8      75     A
9      80     A
10     85     A
11     90     A

===== INPUT (X) =====
    Marks
0      35
1      40
2      45
3      50
4      55
5      60
6      65
7      70
8      75
9      80
10     85
11     90

===== OUTPUT (y) =====
0     C
1     C
2     C
3     B
4     B
5     B
6     B
7     B
8     A
9     A
10    A
11    A
Name: Grade, dtype: object

===== PREDICTED CLASSES =====
['C' 'C' 'C' 'B' 'B' 'B' 'B' 'B' 'A' 'A' 'A' 'A']

===== PREDICTED PROBABILITIES =====
[[5.87457417e-13 3.39645428e-01 6.60354572e-01]
 [2.41036229e-11 3.32484453e-01 6.67515547e-01]
 [1.08369803e-09 3.56177210e-01 6.43822789e-01]
 [9.87041872e-08 7.71955961e-01 2.28043940e-01]
 [5.33357739e-06 9.91307616e-01 8.68704997e-03]
 [2.26570773e-04 9.99546877e-01 2.26552371e-04]
 [9.43681677e-03 9.90557390e-01 5.79297047e-06]
 [2.58761898e-01 7

C:\Users\JANHVI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
