In [8]:
# polynominal regression

# linear -> 1 column 
# multiple -> multiple column
# polynominal -> non-linear

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

data={
    "Experience":[1,2,3,4,5,6,7,8,9,10],
    "salary":[25000,27000,30000,35000,42000,52000,65000,80000,98000,120000]
}

# x
# x2 5,25
# x3 5,25,125

df=pd.DataFrame(data)

print("====DataSet====")
print(df)

# step3: define x and y

x=df[["Experience"]]
y=df["salary"]


# step4 convert to polynomial features

poly=PolynomialFeatures(degree=2)

x_poly=poly.fit_transform(x)


print("===Polynomial Features===")
print(x_poly)


# create model

model=LinearRegression()

model.fit(x_poly,y)

# predict values

y_pred=model.predict(x_poly)

print("===Actual Vs Prediction===")

for actual,predicted in zip(y,y_pred):
    print(f"Actual ={actual} ,Predicted ={np.round(predicted,2)}")

print("===Model Deatils===")
print("Intercept : ",np.round(model.intercept_,2))
print("coefficients : ",model.coef_)
b0+b1x1    

====DataSet====
   Experience  salary
0           1   25000
1           2   27000
2           3   30000
3           4   35000
4           5   42000
5           6   52000
6           7   65000
7           8   80000
8           9   98000
9          10  120000
===Polynomial Features===
[[  1.   1.   1.]
 [  1.   2.   4.]
 [  1.   3.   9.]
 [  1.   4.  16.]
 [  1.   5.  25.]
 [  1.   6.  36.]
 [  1.   7.  49.]
 [  1.   8.  64.]
 [  1.   9.  81.]
 [  1.  10. 100.]]
===Actual Vs Prediction===
Actual =25000 ,Predicted =26163.64
Actual =27000 ,Predicted =26357.58
Actual =30000 ,Predicted =29081.82
Actual =35000 ,Predicted =34336.36
Actual =42000 ,Predicted =42121.21
Actual =52000 ,Predicted =52436.36
Actual =65000 ,Predicted =65281.82
Actual =80000 ,Predicted =80657.58
Actual =98000 ,Predicted =98563.64
Actual =120000 ,Predicted =119000.0
===Model Deatils===
Intercept :  28500.0
coefficients :  [    0.         -3601.51515152  1265.15151515]


In [9]:
# b0+b1x1+b2x^2

print("===Polynomial Equation===")
print(f"salary = {np.round(model.intercept_,2)} + " f"({np.round(model.coef_[1],2)} * Experience) + " f"({np.round(model.coef_[2],2)} * Experience^2)")









===Polynomial Equation===
salary = 28500.0 + (-3601.52 * Experience) + (1265.15 * Experience^2)


In [12]:
new_Exp=pd.DataFrame({"Experience":[11]})

new_exp_poly=poly.transform(new_Exp)

new_salary=model.predict(new_exp_poly)


print("===New prediction for the salary")
print(f"predicted salary for 11 years = {np.round(new_salary[0],2)}")
      


===New prediction for the salary
predicted salary for 11 years = 141966.67
