In [3]:
# NumPy is a Python library.

# list1=[2,5,6,10]
# 1001 1002
# ndArray(20,10,30)
# 1001 1002

# benefits of ndarray
#ndarray -> faster comapre to list
#continuos memory
# large data
# in-built function


# NumPy is used for working with arrays.

# NumPy is short for "Numerical Python".

# ndarray it is faster and easy to use compare to python list

#numpy is created by travis in 2005

# int float string

import numpy as np
# pip install numpy


n=np.array([50,60,70])


x=np.array([10,20,30])#numpy array



print(x[1])


# print arr[row-index][col-index]
# print(y[0][1])#2
print(type(x))
print(x[1])#access
#update
y=[5,6,7]#list
print(y)

a1=np.array([[10,20,30],[1,2,3]])
print(a1)

#MD array

a2=np.array([[[10,20,30],[1,2,3]],[[50,60,70],[5,6,7]]])#1 1 1
print(a2)

print("my value is ",a2[1][1][1])
# print(a2[0,1,2])#3
# arr=np.array([1,2,3])


print(arr)

list1=[25,36,96,85]
print(list1)

#access value of array using index
print(arr[1])

# print(type(arr))

# print(arr.dtype)


#0D array
# arr=np.array([10])

#1D array
# arr=np.array([1,2,3])

#let's create 2D array

#row 0 and row 1
#col 0 , col 1 and col 2
# arr=np.array([[1,2,3],[7,8,9]])

# print(arr)

# row and col start from index 0
# arr[row,col]
# print(arr[0,2])


#access array
arr=np.array([1,25,3,47,10,18])
# arr[0] arr[1] arr[99]

print(arr[1]+arr[2])

#negative index
print(arr[-4])
# range
# start from index 1 and continue till index 3 but not include index3
print(arr[1:3])
#start from index 1 till end
print(arr[1:])
#start from index 0 till 5 not include index 5
print(arr[:5])
#starts with 25 and end with 10
print(arr[-5:-1])

arr=np.array([10,20,30,40,50,60])
#1 till 6 , 2 gap
print(arr[1:6:2])#
wor


20
<class 'numpy.ndarray'>
20
[5, 6, 7]
[[10 20 30]
 [ 1  2  3]]
[[[10 20 30]
  [ 1  2  3]]

 [[50 60 70]
  [ 5  6  7]]]
my value is  6


NameError: name 'arr' is not defined

In [3]:
#print array value with loop
# for in loop
for x in arr:
    print(x)

#shape 
arr1=np.array([[1,2,3],[7,8,9]])
print(arr1.shape)
# 2X3=6

#reshape

arr2=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
newArr=arr2.reshape(4,3)

for x in arr2:
    print(x)
print(newArr)

sum=0
for x in newArr:
    for y in x:
        sum=sum+y
print(sum)        

1
25
3
47
10
18
(2, 3)
10
20
30
40
50
60
70
80
90
100
110
120
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
780


In [4]:
arr3=np.array([1,2,3])

# copyArr=arr3.copy()

copyArr=arr3.copy()

# no1=50
# no2=no1


print(arr3)
print(copyArr)

[1 2 3]
[1 2 3]


In [5]:
mergeArr=np.concatenate((arr3,copyArr,arr3))
print(mergeArr)

[1 2 3 1 2 3 1 2 3]


In [7]:
sortArr=np.sort(mergeArr)

print(sortArr)
print(mergeArr)



[1 1 2 2 3 3]
[1 2 3 1 2 3]


In [45]:
#sorting but without sort (ASC/DESC)

#find max value from array without in-built method
#asc: last index  desc:first index

#find sum of all array element without in-built method

#where
arr=np.array([1,2,5,8,4])

ans=np.where(arr == 5)
print(ans)

print(np.sum(arr))

print(np.mean(arr))

#converts in asc order then then return middle value
print(np.median(arr))

print(np.std(arr))

print(np.max(arr))
print(np.min(arr))





(array([2]),)
20
4.0
4.0
2.449489742783178
8
1


In [ ]:
#numpy is python library
#numpy's array are more faster compare to list
#2005 travis
#numerical python

#diffrence between numpy array and python list
# 1) list result:[50,40,30]    2)arr result:[40 50 70]

import numpy as np
list1=[50,40,30]
print(list1)
print(type(list1))
for x in list1:
    sum+=x
arr1=np.array([40,50,70])

print(arr1)
print(type(arr1))

# 2)if we want to use numpy array then we have to install numpy package in our system ,
# but for list we don't need

# 3)in list we can store diffrent datatypes data , but in array it's not possible
list2=[40,50,"janvi"]
print(list2)

arr2=np.array([10,20,"xyz"])
print(arr2)

#4)numpy have matrix concept 1D, 2D

#5)python list consume huge memory when we use it to store data

#6)using numpy array numerical operations are easy because numpy have so many in-built methods

#7)numpy arrays are more faster compare to python list 

#8)always use numpy array when you are working on huge data

# on the 2D array it's manadatory to maintain same no. of columns
arr3=np.array([[40,50,60,70,80],[1,2,3,4,5]])
print(arr3)

#create numpy array which have 5 values but take that value from user
array_data=[]
# 0 1 2 3 4
for i in range(0,5):
    user_data=int(input("enter data to add inside array"))
    array_data.append(user_data)
# 10 20 30 40
print(array_data) 
# np.array()
#task: take data from user and create 2D array


# np.append()
# row col 2X2
# r1c1:40 r1c2:50 r2c1:60 r2c2:70



[50, 40, 30]
<class 'list'>
[40 50 70]
<class 'numpy.ndarray'>
[40, 50, 'janvi']
['10' '20' 'xyz']
[[40 50 60 70 80]
 [ 1  2  3  4  5]]


In [18]:
#1D 2D 3D MD
a1=np.array([[[1,2],[3,4],[5,6]]])
print(a1)

#ndim
a2=np.array(([1,2,3,4,5]),ndmin=5)
print(a2)

[[[1 2]
  [3 4]
  [5 6]]]
[[[[[1 2 3 4 5]]]]]


In [2]:
#zeros array and ones array
import numpy as np
zero_array=np.zeros(5)
print(zero_array)

one_array=np.ones(3)
print(one_array)

#using zeros and ones you have to create 2D array

#arrange method like range method , start 0
arrange_arr=np.arange(10)
print(arrange_arr)

[0. 0. 0. 0. 0.]
[1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]


In [5]:
#random values
#rand method generate values between o to 1 (positive)
random_arr1=np.random.rand(3)
print(random_arr1)

#randn method generate values near by 0 which may be possible negative between 0 to 1
random_arr2=np.random.randn(4)
print(random_arr2)

#randint method (start,end,total_value)
random_arr3=np.random.randint(50,100,5)
print(random_arr3)

random_array = np.random.randn(2, 3)
print(f"2x3 random array:\n{random_array}")

[0.23531993 0.99879664 0.54054675]
[ 0.620831   -0.19000508 -0.50099265 -0.31810257]
[77 97 63 81 54]
2x3 random array:
[[-1.10790887 -0.89153908  0.93253269]
 [ 0.33287001 -0.20213026 -0.47374453]]


In [5]:
#datatype
#array is container used to store multiple values which have same datatype

import numpy as np
a2=np.array([50,40,80])
print(a2.dtype)

#type casting

newtype=np.array([10,20,30],dtype="f")

print(newtype.dtype)

#type conversion
# a3=np.array([50,40,80],dtype="f")
# print("a3 array : ",a3)
# print(a3.dtype)

a4=np.float32(a2)
print(a4)

# create new array using int data but convert in float
new_array=np.float32(a2)
print("new_array : ",new_array)
print(new_array.dtype)

int64
float32
[50. 40. 80.]
new_array :  [50. 40. 80.]
float32


In [8]:
#numpy arithmetic methods

# a3[0]=a1[0]+a2[0]


add_arr=np.add(a3,a2)
print(add_arr)

#subtract
#multiply
#division
#module

# 3*3*3*3=81
#pow(value,degree)
print(np.pow(3,4))#3*3*3*3

#min,max

a4=np.array([10,78,45,63,25,8])
#min value with it's index
print("minimum value is ",np.min(a4)," and index is ",np.argmin(a4))

#argmax

#sin cos
print(np.sin(a4))


#task:
# craete 2D array create random method

#perform add and multify method on 2D array


arr2=np.array([5,6,10,48,71,52])

print(np.min(arr2), np.argmin(arr2))
max argmax



[100.  80. 160.]
81
minimum value is  8  and index is  5
[-0.54402111  0.51397846  0.85090352  0.1673557  -0.13235175  0.98935825]
5 0


In [57]:
#shape, reshape
#index
a1=np.array([1,2,3,4,5,6])
print(a1[1])

#slice
print(a1[1:4])#start with 1 and end till 4 not include 4
# [1:]
# [:5]
#[0:10:3]#start end step
print(a1[::2])#start with 0 go till end and step 2

for i in a1:
    print(i)

#  task: print 2d array   
# 1 2 3
# 4 5 6

for x,y in np.ndenumerate(a1):
    print(f"index is {x} and value is {y}")


    

2
[2 3 4]
[1 3 5]
1
2
3
4
5
6
index is (0,) and value is 1
index is (1,) and value is 2
index is (2,) and value is 3
index is (3,) and value is 4
index is (4,) and value is 5
index is (5,) and value is 6


In [13]:
#copy vs view
# diffrence is copy method create in array inside memory block , but view methods refers or 
#     points to orignal array
a2=np.array([1,2,3,4])
copy_arr=np.copy(a2)#1 2 3 4

print(a2,copy_arr)
copy_arr[2]=89
print("copy",copy_arr)
print("orignal",a2)

view_arr=a2.view()
print(a2,view_arr)
view_arr[2]=89
print("view",view_arr)
print("ori",a2)

[1 2 3 4] [1 2 3 4]
copy [ 1  2 89  4]
orignal [1 2 3 4]
[1 2 3 4] [1 2 3 4]
view [ 1  2 89  4]
ori [ 1  2 89  4]


In [18]:
#join
a1=np.array([[1,2],[3,4]])
a2=np.array([[10,20],[30,40]])

print(a1)
print(a2)
#hstack
hstack_arr=np.hstack((a1,a2))
print(hstack_arr)
#vstack

vstack_arr=np.vstack((a1,a2))

print(vstack_arr)

#split
a3=np.array([1,2,3,4,10,50,89,78])
split_arr=np.array_split(a3,3)
print(split_arr)
print(a3)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]
[[ 1  2 10 20]
 [ 3  4 30 40]]
[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]
[array([1, 2, 3]), array([ 4, 10, 50]), array([89, 78])]
[ 1  2  3  4 10 50 89 78]


In [2]:
#search 
import numpy as np
a1=np.array([50,78,96,12])
x=np.where(a1 == 12)
print(x)


#task: print index with even values from array

(array([3]),)


In [16]:
#search_sorted it returns index at where i can insert that value in array , but array must be stored in ASC order
a2=np.array([10,20,30,50])
y=np.searchsorted(a2,40)
print(y)
# append()
#sort()
#task: sort alphabate array

#filter used to filter array data
filter_arr=np.array([50,60,-80,-1])
f=[True,True,False,False]
new_arr=filter_arr[f]
print(new_arr)

#task:take 10 values from user and add that value in array and filter the data conditions is: >40

#shuffle
shuffle_arr=np.array([10,20,30,80])
np.random.shuffle(shuffle_arr)
print(shuffle_arr)

#unique
emp_ID=np.array([101,500,105,502,101,800,906])
z=np.unique(emp_ID)
print(z)

#resize
resize_arr=np.array([101,500,105,502,101,800,906,555])
x1=np.resize(resize_arr,(2,4))
print(x1)

3
[50 60]
[20 30 80 10]
[101 105 500 502 800 906]
[[101 500 105 502]
 [101 800 906 555]]


In [1]:
#insert(arr,position,value)


my_arr=np.array([101,500,105,502,101,800,906,555])
new_arr=np.insert(my_arr,3,1000)
print(new_arr)

#2D array 
#     0  1  2
# 0:  25 96 78
# 1:  45 56 21

#append(arr_name,value)
#remove value from array
new_a=[10,20,30,40]
d=np.delete(new_a,1)
print(d)

new_array=np.matrix([[1,2,3],[4,5,6]])
print(new_array)

# *
# arr1.dot(arr2)

NameError: name 'np' is not defined